---
openapi: 3.1.0
info:
  title: FastAPI Prosept Dealer
  version: 0.1.0
paths:
  "/token":
    post:
      summary: Получение JWT токена
      description: Аутентификация пользователя, получение JWT-токена.
      operationId: login_for_access_token_token_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LoginRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Token"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/users/":
    post:
      summary: Регистрация пользователей
      description: Регистрация нового пользователя.
      operationId: register_user_users__post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserCreate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/dealers":
    get:
      summary: Список диллеров
      description: Выводит объекты модели «MarketingDealer»
      operationId: read_dealers_dealers_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/MarketingDealerModel"
                type: array
                title: Response Read Dealers Dealers Get
  "/products":
    get:
      summary: Список товаров Просепт
      description: Выводит объекты модели «MarketingProduct»
      operationId: read_products_products_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/MarketingProductModel"
                type: array
                title: Response Read Products Products Get
  "/dealerprice":
    get:
      summary: Список товаров от парсера
      description: Выводит объекты модели «MarketingDealerPrice»
      operationId: read_dealerprice_dealerprice_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/MarketingDealerPriceModel"
                type: array
                title: Response Read Dealerprice Dealerprice Get
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    LoginRequest:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
      type: object
      required:
      - username
      - password
      title: LoginRequest
    MarketingDealerModel:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
      - id
      - name
      title: MarketingDealerModel
    MarketingDealerPriceModel:
      properties:
        id:
          type: integer
          title: Id
        product_key:
          type: string
          title: Product Key
        price:
          type: number
          title: Price
        product_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Product Url
        product_name:
          type: string
          title: Product Name
        date:
          type: string
          format: date-time
          title: Date
        dealer_id:
          type: integer
          title: Dealer Id
      type: object
      required:
      - id
      - product_key
      - price
      - product_name
      - date
      - dealer_id
      title: MarketingDealerPriceModel
    MarketingProductModel:
      properties:
        id:
          type: integer
          title: Id
        article:
          type: integer
          title: Article
        ean_13:
          type: string
          title: Ean 13
        cost:
          anyOf:
          - type: number
          - type: 'null'
          title: Cost
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        min_recommended_price:
          anyOf:
          - type: number
          - type: 'null'
          title: Min Recommended Price
        recommended_price:
          anyOf:
          - type: number
          - type: 'null'
          title: Recommended Price
        category_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Category Id
        ozon_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Ozon Name
        name_1c:
          anyOf:
          - type: string
          - type: 'null'
          title: Name 1C
        wb_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Wb Name
        ozon_article:
          anyOf:
          - type: string
          - type: 'null'
          title: Ozon Article
        wb_article:
          anyOf:
          - type: string
          - type: 'null'
          title: Wb Article
        ym_article:
          anyOf:
          - type: string
          - type: 'null'
          title: Ym Article
        wb_article_td:
          anyOf:
          - type: string
          - type: 'null'
          title: Wb Article Td
      type: object
      required:
      - id
      - article
      - ean_13
      title: MarketingProductModel
    Token:
      properties:
        access_token:
          type: string
          title: Access Token
        token_type:
          type: string
          title: Token Type
      type: object
      required:
      - access_token
      - token_type
      title: Token
    User:
      properties:
        username:
          type: string
          title: Username
        id:
          type: integer
          title: Id
      type: object
      required:
      - username
      - id
      title: User
    UserCreate:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
      type: object
      required:
      - username
      - password
      title: UserCreate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
