---
openapi: 3.1.0
info:
  title: FastAPI Prosept Dealer
  version: 0.1.0
paths:
  "/api/v1/matching":
    get:
      tags:
      - Матчинг
      summary: Список наиболее вероятных карточек производителя для каждой карточки
        дилера
      description: |-
        - Получаем все объекты модели «MatchingProductDealer».
        - В каждом объекте одна карточка дилера и пять карточек товаров Просепт.
      operationId: read_dealer_product_api_v1_matching_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/MatchingProductDealerModel"
                type: array
                title: Response Read Dealer Product Api V1 Matching Get
  "/api/v1/matching/{dealer_product_id}":
    post:
      tags:
      - Матчинг
      summary: Сохранение карточки после обработки оператором
      description: |-
        - Удаляем объект из модели «MatchingProductDealer», по значению
          поля dealer_product_id. И создаем новую запись в
          «MatchPositiveProductDealer» с карточкой Просепт, полученной
          по значению prosept_id.
      operationId: post_product_api_v1_matching__dealer_product_id__post
      parameters:
      - name: dealer_product_id
        in: path
        required: true
        schema:
          type: integer
          description: ID карточки дилера
          title: Dealer Product Id
        description: ID карточки дилера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProductData"
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MatchPositiveProductDealerModel"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    patch:
      tags:
      - Матчинг
      summary: Перенести карточку дилера в конец списка
      description: |-
        - Меняем поле order в модели «MatchingProductDealer», что-бы при сортировке
          по этому полю изменённый объект оказался в конце списка.

        - Переносим выбранную карточку дилера в конец списка.
      operationId: patch_product_api_v1_matching__dealer_product_id__patch
      parameters:
      - name: dealer_product_id
        in: path
        required: true
        schema:
          type: integer
          description: ID карточки дилера
          title: Dealer Product Id
        description: ID карточки дилера
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    delete:
      tags:
      - Матчинг
      summary: Удалить карточку дилера
      description: |-
        - Удаляем объект модели «MatchingProductDealer», по значению
          поля dealer_product_id. И создаем новую запись в
          «DelMatchingProductDealer».

        - Удаляем карточку дилера и 5 связанных с ним карточек товаров Просепт.
      operationId: delete_product_api_v1_matching__dealer_product_id__delete
      parameters:
      - name: dealer_product_id
        in: path
        required: true
        schema:
          type: integer
          description: ID карточки дилера
          title: Dealer Product Id
        description: ID карточки дилера
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/statistics":
    get:
      tags:
      - Статистика
      summary: Статистика работы оператора
      description: Собираем статистику по работе оператора.
      operationId: get_statistics_api_v1_statistics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/StatisticsData"
components:
  schemas:
    DealerProductModel:
      properties:
        id:
          type: integer
          title: Id
          description: ID объекта в БД
        dealer_name:
          type: string
          title: Dealer Name
          description: Название дилера
        product_name:
          type: string
          title: Product Name
          description: Название товара
        price:
          type: number
          title: Price
          description: Цена
        product_url:
          type: string
          title: Product Url
          description: Ссылка на товар
      type: object
      required:
      - id
      - dealer_name
      - product_name
      - price
      - product_url
      title: DealerProductModel
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MatchPositiveProductDealerModel:
      properties:
        id:
          type: integer
          title: Id
          description: ID объекта в БД
        dealer_product_id:
          type: integer
          title: Dealer Product Id
          description: ID карточки дилера
        product_id:
          type: integer
          title: Product Id
          description: ID товара Просепт
      type: object
      required:
      - id
      - dealer_product_id
      - product_id
      title: MatchPositiveProductDealerModel
    MatchingProductDealerModel:
      properties:
        id:
          type: integer
          title: Id
          description: ID объекта в БД
        dealer_product:
          allOf:
          - "$ref": "#/components/schemas/DealerProductModel"
          description: Карточка товара дилера
        products:
          items:
            "$ref": "#/components/schemas/ProseptProductModel"
          type: array
          maxItems: 5
          minItems: 5
          title: Products
          description: Список который содержит пять товаров от Просепт
      type: object
      required:
      - id
      - dealer_product
      - products
      title: MatchingProductDealerModel
    ProductData:
      properties:
        prosept_id:
          type: integer
          title: Prosept Id
          description: ID карточки товара от Просепт.
      type: object
      required:
      - prosept_id
      title: ProductData
    ProseptProductModel:
      properties:
        id:
          type: integer
          title: Id
          description: ID объекта в БД
        article:
          type: integer
          title: Article
          description: Артикул товара
        cost:
          type: number
          title: Cost
          description: Цена
        name_1c:
          type: string
          title: Name 1C
          description: Название товара
      type: object
      required:
      - id
      - article
      - cost
      - name_1c
      title: ProseptProductModel
    StatisticsData:
      properties:
        total_cards_checked:
          type: integer
          title: Total Cards Checked
          description: Общее количество проверенных карточек
        accepted_cards:
          type: integer
          title: Accepted Cards
          description: Количество принятых карточек
        delete_cards:
          type: integer
          title: Delete Cards
          description: Количество неподходящих карточек
        postponed_cards:
          type: integer
          title: Postponed Cards
          description: Количество отложенных карточек
        percentage_accepted_cards:
          type: number
          title: Percentage Accepted Cards
          description: Процент принятых карточек
      type: object
      required:
      - total_cards_checked
      - accepted_cards
      - delete_cards
      - postponed_cards
      - percentage_accepted_cards
      title: StatisticsData
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
